### ISSUE TITLE
Can't seem to find starting window, crashes when Auto starts

### ISSUE THREAD

**Issue by MisterStrawberryMan** [tiemonl/Bit-Heroes-Fishing-Bot#1]
The bot can't seem to calibrate correctly, still shows x=0, y=0

**To Reproduce**
Using both chrome and steam on suggested settings and exact same spot for fishing didn't work. Bot wouldn't calibrate.

![screenshot 209](https://user-images.githubusercontent.com/40729863/42131501-fc608b76-7cb7-11e8-8e1a-156426e9753a.png)

**Comment by tiemonl** [comment]
I assume you have 2+ monitors. To solve this currently, the program searches on the **main** monitor. So, put Bit Heroes on your main screen. It only shows x=0, y=0 when there are two monitors or something is covering the start button. 

I will work on a fix today, and push it out in a new release, sorry for the hassle. Let me know if that works for you meanwhile.

**Comment by tiemonl** [comment]
Download the [latest release](https://github.com/tiemonl/Bit-Heroes-Fishing-Bot/releases/tag/v1.1.0) for fix.
