### ISSUE TITLE
Doesn't go past the item screen if it's not a fish

### ISSUE THREAD

**Issue by Echonium** [tiemonl/Bit-Heroes-Fishing-Bot#10]
**Describe the bug**
When I fish something other than fishes (can, stick, balloon...), it doesn't go past the "trade" screen. The soft goes to the next "waiting for cast result"

**Version(please complete the following information):**
 - Steam

**Additional context**
W7 x64

![capture](https://user-images.githubusercontent.com/42712174/45100266-6e790300-b129-11e8-9a5a-7c8eab41ead0.PNG)

**Comment by tiemonl** [comment]
I am aware of the issue. similar to #8 and #2... will try to work on a fix when i have time, potentially this weekend.

**Comment by tiemonl** [comment]
@Echonium I sent you a pm on discord with a build for you to try out. Could you try it and let me know if the error is solved?
