### ISSUE TITLE
Program becomes unresponsive once Auto mode is initiated 

### ISSUE THREAD

**Issue by Cannavash** [tiemonl/Bit-Heroes-Fishing-Bot#11]
The program becomes unresponsive when initiating auto mode.
 
So I go to steam, boot the BH, then boot the .exe

The I select steam in the app, Then the blue rod, then the find start botton, then hit start on BH. Then hit the auto mode button, and the app freezes.

I am running win10-64bit and on a i5-8300 and a gtx 1050ti.

Any suggestions on how to get this working would be appreicated.

I will mention I ran through the windows legacy compatibility options, none of them resolved the issue.

Thanks!

 

![untitled](https://user-images.githubusercontent.com/43246387/45501349-e7421580-b74e-11e8-84a4-eb9cc43212ae.png)

**Comment by tiemonl** [comment]
Hey, can you check your display settings by right clicking your desktop and clicking "display settings".
Once in there, can you check that your resolution is the default resolution of the monitor the game is on and that **Scale and Layout** is at 100%?

**Comment by Cannavash** [comment]
Hello,

I Got it working right after I posted the bug report. I was about to update
what my issue turned out to be, It turns out my GPU was rendering in
1600x900 instead of the 1080.... Once I changed that it started working
fine. Thanks you for your prompt response!

**Comment by tiemonl** [comment]
no worries, glad it's working for you. Enjoy the program!
