### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Lawlzer** [tiemonl/Bit-Heroes-Fishing-Bot#16]
**Describe the bug**
Basically, the program crashes (and it clicks in the wrong place, first)

**To Reproduce**
http://prntscr.com/le9yd7
Get to here, calibrate it, click "Auto mode"...
then the fishing script stops responding, and it clicks about 1/5 too low on my screen, too. (Which then un-focuses the program and pushes it to the background, maybe that's what is causing the crash?)

**Expected behavior**
It should.. do the script stuff?

**Screenshots**
http://prntscr.com/le9yd7

**Version(please complete the following information):**
Steam, Fish version 1.2.4

**Additional context**

**Comment by tiemonl** [comment]
Hey, this seems like an issue I never got around to fixing. You want to go to display settings and make sure the scale and layout is 100% and you're at default resolution. Refer to this screenshot below:

![displaySettings](https://i.imgur.com/9SVnEmJ.png)

Let me know if that solves the issue for you!

**Comment by tiemonl** [comment]
I'm going to assume this was the issue and consider it fixed. I will close it. If you're still having issues, feel free to open it back up!
