### ISSUE TITLE
Bot does not catch fish after casting

### ISSUE THREAD

**Issue by fluffypandaop** [tiemonl/Bit-Heroes-Fishing-Bot#17]
**Describe the bug**
The program will not press catch fish, lets the time run out.

**To Reproduce**
Using fisher v1.2.4, use auto mode.

**Expected behavior**
Expected the bot to catch fish and move onto next bait, but lets time run out and does not continue

**Screenshots**

![bug report](https://user-images.githubusercontent.com/44881395/48228881-bef82100-e363-11e8-8b33-a78c0db71a2f.jpg)

**Version(please complete the following information):**
 Kongregate on Google Chrome.

**Comment by tiemonl** [comment]
Hey!

You have to use normal zoom for the bot to work. You are zoomed out on the chrome window. Let me know if that solves the issue for you!

**Comment by fluffypandaop** [comment]
I'm actually on a 2-in-1 tablet/laptop, and that is my 100% zoom. Should I fiddle around with the browser zoom settings?

**Comment by tiemonl** [comment]
Yes, that's what I meant. Your chrome window is zoomed out. Look at the URL bar in your screenshot (before your edit). 

![image](https://user-images.githubusercontent.com/29804333/48233864-f62afa00-e384-11e8-9508-2eb251db2287.png)

Make sure you set that to 100% and it should work!

**Comment by fluffypandaop** [comment]
oh you're right, I feel dumb now I forgot to check that haha

**Comment by tiemonl** [comment]
No worries, it happens!
