### ISSUE TITLE
fisher bot does not work

### ISSUE THREAD

**Issue by lars1999vk** [tiemonl/Bit-Heroes-Fishing-Bot#18]
when i click find location it gathers some coord (no idea if they are the right ones). if i hit auto fishing the programs clicks way under the ''start'' buton and clicks on the bottom of my screen. at the same time the app freezes and does not unfreeze. 

i have tried running both steam and kong and also tried older versions. i have a single monitor (laptop) and im running on win10.

my discord tag is -----

**Comment by tiemonl** [comment]
Hey, are you clicking start on the screen shown in the README? If so, can you make sure that you are on your default screen resolution and that scaling is set to 100% as shown in this picture? ![Pic](https://support.wildtangent.com/hc/article_attachments/360001811946/resolution_settings.png)

**Comment by tiemonl** [comment]
Fixed on discord.
Scaling was 125%, changed to 100% and resolved the issue.
