### ISSUE TITLE
software wont start

### ISSUE THREAD

**Issue by bobhisays** [tiemonl/Bit-Heroes-Fishing-Bot#20]
When I click Find Start Location, it gives me an error, saying Start Button cannot be found

<img width="598" alt="bug" src="https://user-images.githubusercontent.com/48231734/53778497-cc588e80-3eb1-11e9-9627-fe22eb191f09.PNG">

**Comment by bobhisays** [comment]
nvm I didn't change to 100%, closed

**Comment by tiemonl** [comment]
Glad you got it worked out! Let me know if you have any other questions.
