### ISSUE TITLE
Bot doesn't work

### ISSUE THREAD

**Issue by Sonar522** [tiemonl/Bit-Heroes-Fishing-Bot#22]
**Describe the bug**
No matter which one I try (Kong or Steam) my character just stands there and the bot never starts and it goes into a Not Responding state.  It even sometimes in Chrome opens a random new tab to a random game page.  I have correctly followed the steps for both ways yet the bot still does not perform.

**To Reproduce**
Steps to reproduce the behavior, i.e:
1. Go to Bit Heroes
2. Click on Start Fishing once in spot referenced in directions
3. Open Bot, Select correct items and set cast spot
4. Start Auto on Bot
5. Bot hangs and never starts

**Expected behavior**
Bot start and fish for me.

**Screenshots**
Add a screenshot of your Bit Heroes screen and a screenshot of the program GUI.

**Version(please complete the following information):**
 - Steam and Kongregate

**Additional context**

**Comment by tiemonl** [comment]
Hey, 

A few things. Please make sure your windows zoom settings are set to 100% and that you are on your monitors default resolution as such: 
![windowsZoomSettings](https://user-images.githubusercontent.com/29804333/54868250-f2f74000-4d60-11e9-9900-2669ebd1b859.PNG)

For **Steam**. Make sure the game is set to 800x600 as such:
![gameZoomSetting](https://user-images.githubusercontent.com/29804333/54868365-1969ab00-4d62-11e9-91a0-ca42cc5cf21d.png)

For **Kongregate**. Make sure the browser zoom settings are set to 100%. For example: Chrome:
![browserZoomSetting](https://user-images.githubusercontent.com/29804333/54868448-effd4f00-4d62-11e9-9b3c-d1b9de431712.png)

I will update the README as I don't clearly say that in there. If that is not the issue, let me know and I can look into it more.

**Comment by Sonar522** [comment]
The zoom settings was it! It was somehow set on 125%. Working fine now.

**Comment by tiemonl** [comment]
Glad to hear it's working. I may get around to fixing it in the summer when I have more time, but for the time being I updated the README for future use for other people who have this issue.
