### ISSUE TITLE
Make it easier to integrate with Fishing Bot

### ISSUE THREAD

**Issue by ilpersi** [tiemonl/Bit-Heroes-Fishing-Bot#24]
**Is your feature request related to a problem? Please describe.**
Hi tiemonl, first of all let me compliment you for this amazing tool. 😄 

Let me introduce me: I am ilpersi, current maintainer of [BHBot](https://github.com/ilpersi/BHBot). As you can see this is a helper tool for Bit Heroes that supports users with leveling.

The bot has many different features and it is also able to collect fishing baits daily. If properly configured, the bot can also run unattended: when this happens, a lot of baits are collected and not used.

Currently, the only possible way to consume all the baits is to stop the bot and manually run your fishing bot. It works fine and if this could be done unattended it would be wonderful.

**Describe the solution you'd like**
It would be nice to have some kind of integration features.

They could be simple:
- being able to set up the bot using command line arguments (to set up parameters like the rod type and the number of baits)
- being able to autostart the bot (maybe always with some cmd line argument)
- having a return value from the bot to understand if there were issues

Or if you prefer also complex like DLL calls, Pipe integration or whatever is your preferred way to do that as long as it is language independent (BHBot is developed in Java).

**Describe alternatives you've considered**
We currently support a hacky integration with your fishing bot using an AutoIT script that sets up the bot and runs it simulating mouse clicks. As you can guess, this is not the best solution out there, that is why we are asking for some kind of integration capabilities.

I hope we can find a way to integrate the tools. Do not hesitate to let me know if you have any doubt.

Thank you!

**Comment by tiemonl** [comment]
Hey, that sounds like a good idea. One thing I would like to ask you if you don't mind is to give me credit on your bot if you are using my fisher, I would appreciate it! 😃 As far as the integration, message me on discord, `purplethong#0069` we can come up with a solution there!

**Comment by tengen-toppa** [comment]
I hope bot could support Kartridge platform first, the resolution is fixed, so it should less issue than browser.
Also I hope the react could more accurate.
Personally I would love to buy/support by 30 USD from my credit card if mentioned above could happened.

**Comment by tiemonl** [comment]
@tengen-toppa I wasn't aware of issues with Kartridge as I no longer play the game and I never got any issues here about it. I can work on that. 

The resolution is a weird issue, and I might have to rework some of the original logic to fix that one. It's doable, but it's definitely tricky. I'll take a look at it.

The reaction problem can't really be solved as the casting bar is not on a set time. I've put an average time by testing how long it takes to get from a full bar to empty out and fill back up on different computers at different times. From there, I introduced the Debug options where a user can adjust the timing slightly to perfect it based on their cast bar timer (I'm not sure how many people actually utilize the debug tool as I haven't implemented any analytics in my tool). I would be open to any suggestions on how to improve that section of the fisher program or any other part. Let me know.

**Comment by ilpersi** [comment]
@tiemonl thank you for your answer!

As we currently rely on an AutoIt script to make this work, we do not support this feature officially in our bot (too hacky), so we were giving you credit in our Wiki page dedicated to [Fishing](https://github.com/ilpersi/BHBot/wiki/Fishing): I reviewed that to make it more clear, I hope you are ok with this.

I am a bit concerned on privacy about contacting you on Discord as I would like to keep my in-game identity private: is there any other way I can get in touch with you? We have a [gitter channel](https://gitter.im/BHBot/community) and from there you can get in touch with me directly, does this sounds good to you?
