### ISSUE TITLE
Attempting to use the 'Get Times' option freezes everything.

### ISSUE THREAD

**Issue by hollowharkov** [tiemonl/Bit-Heroes-Fishing-Bot#26]
**Describe the bug**
Clicking Get Times causes the bot to crash

**To Reproduce**
Steps to reproduce the behavior, i.e:
1. Go to Debug Options
2. Click on Get Times

**Expected behavior**
Bot should find the average casting time

**Screenshots**
https://i.imgur.com/1P1TAaX.png

**Version(please complete the following information):**
Kongregate

**Additional context**
Chromium v69.0.3497.0

**Comment by tiemonl** [comment]
I can't seem to reproduce this error... does the program work without using get times and/or has get times worked for you before?

**Comment by hollowharkov** [comment]
I am able to use the program without it, but it only reaches 43/48 every time the bot casts. If you need any other relevant info feel free to ask. I was also able to replicate the bug on steam.

**Comment by tiemonl** [comment]
Let me see if I can mess with some logic in the code to hopefully fix it for you. I'll send you an executable when I get around to it. Meanwhile, you could try to adjust the timer up/down to fine tune it manually.
