### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by guipaiva** [tiemonl/Bit-Heroes-Fishing-Bot#27]
Fishing Bot not working on Ubuntu Linux with Wine.

I'm playing on kongregate.
It finds the start location but when I click Auto Mode it moves the mouse cursos to the start button and then the program crash. 

Please considere making a linux version, or at least try to fix this. Thank you.

**Comment by tiemonl** [comment]
#13 is very similar... i might actually take the time to work on this since there is a bigger audience. i'll probably make a java .jar. It most likely won't be as polished as the windows version, but that's problems for later. once i start working on it, i'll probably release a beta build for people to use on mac/linux and get feedback from there.

**Comment by guipaiva** [comment]
Is very similar but in linux it looks like having problems on the click action, everything else appears to work fine.
Suggestion: Maybe you could use xdotool to emulate moving and clicking the mouse on Linux. Thanks for the answer.

**Comment by tiemonl** [comment]
> Suggestion: Maybe you could use xdotool to emulate moving and clicking the mouse on Linux. Thanks for the answer.

I could, but the original project is a C# .NET Windows Form. xdotool is a bash command line tool, therefore I cannot integrate it into the original solution. Java runs on every OS, therefore a .jar would work. I just have to convert my original solution to Java. It'll be a bit tedious, but doable.

**Comment by guipaiva** [comment]
> I could, but the original project is a C# .NET Windows Form. xdotool is a bash command line tool, therefore I cannot integrate it into the original solution.

The suggestion was for the Linux version program.
Anyway, it doesn't have to be so polished as long as it works :D

**Comment by tiemonl** [comment]
Refer to #29
