### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by deividaslord** [tiemonl/Bit-Heroes-Fishing-Bot#28]
Client do not respond (crash)10/10 times after auto mode is turned on

![11](https://user-images.githubusercontent.com/24681210/64075533-d40abb80-ccb9-11e9-8ed9-a11d31fe31d6.PNG)

**Comment by tiemonl** [comment]
Are you clicking auto mode on that screen? or do you click it on the start screen? Also, which platform are you on?

**Comment by deividaslord** [comment]
i selected steam, wooden fishing rod, 5 bait, fint start locatioon and then "auto mode". It wil start fishing but wont go further, than this(the screen on the picture). im using windows 10, steam, pc. :p

**Comment by tiemonl** [comment]
If you are using steam, did you select 800x600 resolution?
