### ISSUE TITLE
Can't find start button

### ISSUE THREAD

**Issue by ToastyDaDragon** [tiemonl/Bit-Heroes-Fishing-Bot#39]
**Describe the bug**
I cannot fish due to it not finding button, i just downloaded and am trying to get it working for the first time. I am on mac using a chrome window via kongregate

**To Reproduce**
Steps to reproduce the behavior, i.e:

**Expected behavior**

**Screenshots**
Add a screenshot of your Bit Heroes screen and a screenshot of the program GUI.
![Screen Shot 2019-09-21 at 4 56 03 PM](https://user-images.githubusercontent.com/20297372/65380448-d0eb6580-dc90-11e9-9da2-d067f3d0963c.png)
![Screen Shot 2019-09-21 at 4 55 39 PM](https://user-images.githubusercontent.com/20297372/65380449-d3e65600-dc90-11e9-8f83-010a32ef411b.png)

**Version(please complete the following information):**
 - Kongregate

**Additional context**
i am mac user

**Comment by tiemonl** [comment]
Hey,

Are you connected to an external monitor? If so, did you try on your primary monitor and/or each monitor?

If you are not connected to an external monitor, could you please:
 - open the `Digital Color Meter` app and select `Display in Generic RGB`
 - Take a screenshot like you did on the start screen
 - Hover your mouse over the darker green bottom half of the start button and tell me the RGB value being displayed by the Color Meter app?

**Comment by ToastyDaDragon** [comment]
102
140
19
is rgb

**Comment by ToastyDaDragon** [comment]
also no external monitor

**Comment by tiemonl** [comment]
Hmm, those colors are pretty off what they should be... If you go into `System Preferences` > `Displays` > `Color` What profile is selected?

**Comment by ToastyDaDragon** [comment]
color lcd

**Comment by tiemonl** [comment]
Could you add me on discord `purplethong#0069` for easier communication?

**Comment by ToastyDaDragon** [comment]
yeah
