### ISSUE TITLE
Application freezes when used normally

### ISSUE THREAD

**Issue by KevinEG** [tiemonl/Bit-Heroes-Fishing-Bot#4]
**Describe the bug**
Application freezes when used up until Auto Mode was pressed

**To Reproduce**
Use the program normally up until Auto mode

**Expected behavior**
Since couple days ago the program now crashes / freezes when you pressed auto mode

**Screenshots**
![image](https://user-images.githubusercontent.com/7221190/43837982-5cef04ea-9b44-11e8-966f-946175ae1e6b.png)

**Version(please complete the following information):**
 - Steam

**Additional context**
Is it no longer working?

**Comment by tiemonl** [comment]
If you can give me your discord username, I can message you and try to debug this a bit more easily. Thanks and sorry for the issues.

**Comment by KevinEG** [comment]
VolkFrost#8602

I'm guessing it's an isolated issue?

**Comment by tiemonl** [comment]
Fixed.
