### ISSUE TITLE
Technical question

### ISSUE THREAD

**Issue by Simonero14** [tiemonl/Bit-Heroes-Fishing-Bot#44]
Good morning, developers. I am interested to know if the fishing bot is detectable if I use it or in some way my character is at risk of being banned by Kongregate. I understand that as it is a program for external use, it should not be allowed, and even if it is not a hack as such, perhaps if there is a risk of banning.

Could you answer that question? Thanks a lot!

**Comment by tiemonl** [comment]
Good morning.

People have reported this program and developers are aware of it. Essentially this mimics a player. I never guaranteed 100% catch rate or mythic fish only. This program just does what a player would, just better. As far as I know, no one has been banned for using it so there is essentially no risk. I'll close this issue, but if I didn't answer your question, feel free to reopen it.
