### ISSUE TITLE
Possible legendary rod fishing issue

### ISSUE THREAD

**Issue by xsysceo** [tiemonl/Bit-Heroes-Fishing-Bot#5]
**Describe the bug**
The program has never cast my Legendary fishing rod to maximum (56), usually cast between 45 and 50. I have tried to adjust the Option delay, but makes no difference

**To Reproduce**
Steps to reproduce the behavior, i.e:

**Expected behavior**
With my common and rare rods, the program regularly cast to the rods maximum, I expect the program to do the same for the Legendary rod.

**Screenshots**
Add a screenshot of your Bit Heroes screen and a screenshot of the program GUI.

**Version(please complete the following information):**
 - Steam

**Additional context**

**Comment by tiemonl** [comment]
Could you give me some more information? What version of the bot are you using?

**Comment by tiemonl** [comment]
Closed as I figure this user was experiencing the same issue as #6 and #4. now fixed with e2d83ad
