### ISSUE TITLE
Software freeze on Windows 7 - second round

### ISSUE THREAD

**Issue by ValaraukarNoir** [tiemonl/Bit-Heroes-Fishing-Bot#8]
Same bug as described before : after performing the fishing correctly, it freeze at the screen that display the fishing's result. This time i tryed to perform 1 fishing only, then manually do "escape" to return to the fishing screen, then tryed to relaunch the fishing 1 time (by clicking on "auto mode") and i obtained this error : 

[
![image](https://user-images.githubusercontent.com/42716906/44644475-7f60a080-a9d4-11e8-81f6-33c020cc6e31.png)
](url)

> Consultez la fin de ce message pour plus de détails sur l'appel du débogage
> juste-à-temps (JIT) à la place de cette boîte de dialogue.
> 
> ************** Texte de l'exception **************
> System.InvalidOperationException: BackgroundWorker est actuellement occupé et ne peut pas exécuter plusieurs tâches simultanément.
>    à System.ComponentModel.BackgroundWorker.RunWorkerAsync(Object argument)
>    à System.ComponentModel.BackgroundWorker.RunWorkerAsync()
>    à fisher.Form1.autoBtn_Click(Object sender, EventArgs e)
>    à System.Windows.Forms.Control.OnClick(EventArgs e)
>    à System.Windows.Forms.Button.OnClick(EventArgs e)
>    à System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>    à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    à System.Windows.Forms.Control.WndProc(Message& m)
>    à System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    à System.Windows.Forms.Button.WndProc(Message& m)
>    à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Assemblys chargés **************
> mscorlib
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.7.2650.0 built by: NET471REL1LAST_B
>     CodeBase : file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> fisher
>     Version de l'assembly : 1.0.0.0
>     Version Win32 : 1.0.0.0
>     CodeBase : file:///C:/07-Jeux/Bit-Heroes-Fishing-Bot-master/fisher-v1.2.3.exe
> ----------------------------------------
> System.Windows.Forms
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.7.2634.0 built by: NET471REL1LAST_C
>     CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.7.2634.0 built by: NET471REL1LAST_C
>     CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.7.2634.0 built by: NET471REL1LAST_C
>     CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.7.2558.0 built by: NET471REL1
>     CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Core
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.7.2634.0 built by: NET471REL1LAST_C
>     CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Xml
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.7.2634.0 built by: NET471REL1LAST_C
>     CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> System.resources
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.6.1055.0 built by: NETFXREL2
>     CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.resources.dll
> ----------------------------------------
> System.Windows.Forms.resources
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.6.1055.0 built by: NETFXREL2
>     CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
> ----------------------------------------
> mscorlib.resources
>     Version de l'assembly : 4.0.0.0
>     Version Win32 : 4.6.1055.0 built by: NETFXREL2
>     CodeBase : file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll
> ----------------------------------------
> 
> ************** Débogage JIT **************
> Pour activer le débogage juste-à-temps (JIT), le fichier de configuration pour cette
> application ou cet ordinateur (machine.config) doit avoir la valeur
> jitDebugging définie dans la section system.windows.forms.
> L'application doit également être compilée avec le débogage
> activé.
> 
> Par exemple :
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> Lorsque le débogage juste-à-temps est activé, les exceptions non gérées
> seront envoyées au débogueur JIT inscrit sur l'ordinateur
> plutôt que d'être gérées par cette boîte de dialogue.
> 

**Step To Reproduce**

1. click "find start location"
2. Click "auto mode"
3. at the fishing's result screen, perform manually the "click" or "escape" to be back to the screen that start fishing action (because the soft can't escape this screen by his own)
4. Click on the "fisher v1.2.3" windows and on the "auto mode" button - then message/error shown above appear.

**Screenshots** - **Version**
Same situation as described yesterday with same W7 X64 config - tested on Kongregate AND Steam

**Version(please complete the following information):**
 - Steam or Kongregate

Bon courage, je testerais sur W10 ton appli ;)
Bonne journée

**Comment by tiemonl** [comment]
This error occurs when users manually input or click something in bit heroes "desyncing" the program. Then when you try to run another auto fish, the original thread hasn't finished as it was desynced and it is stuck hanging. Therefore, another thread cannot start because the original thread is not done. Can you show me the exact screen it freezes on where you have to manually click? 

Also, can you try to change your game language to english to see if the font changes the size of buttons?

**Comment by D1sarm** [comment]
I have the same issue with bot. Using windows 10. I tried different versions, but it's not working.
I recorded video, check that out if u're interested to help us 😉
https://youtu.be/nr9G0n9OkPY

**Comment by tiemonl** [comment]
Hey, @D1sarm thanks for the video. Very useful for me. Quick questions:

- Is the steam window 800x600?
- Are you on one monitor?
- The monitor that you are using, is it on default resolution and 100% zoom? (display settings on windows 10)

**Comment by D1sarm** [comment]
On video resolution was 800x480, but after that i tried 800x600, and got the same problem. Also tried on kongregate.com, but bot isn't working :(
Yes, i'm using 1 monitor.
Yes, my monitor resolution is default (1920x1080), and zoom is 100%. I attached a screenshot. 
https://imgur.com/a/wsBYUg5

**Comment by tiemonl** [comment]
I will look into it. but I can't reproduce it on my end. so not sure why its happening.

**Comment by D1sarm** [comment]
Ask me. I'll try to help if you need)

**Comment by tiemonl** [comment]
@D1sarm actually, I may have an idea as to why. When you are playing the game, can you make sure the keyboard is in English. The program is sending a space key press and if the keyboard input isn't English that may be a reason it is breaking there. Because watching your video again, the program is sending space because you can see in the info section it is still continuing, but not actually pressing the buttons.

**Comment by D1sarm** [comment]
Nah, same issue. You could be right, but. As you can see on video bot can catch a fish even if my keyboard input isn't English. So...

**Comment by tiemonl** [comment]
@D1sarm yeah, that's a good point. im pressing space to catch and cast as well, so that breaks that theory. I'll look into it. can you send me your discord tag so that I can send you updated versions of the bot to see if it solves the issue?

**Comment by D1sarm** [comment]
Of course -------
