### ISSUE TITLE
The bot stopped to working :/

### ISSUE THREAD

**Issue by refoz** [tiemonl/Bit-Heroes-Fishing-Bot#9]
**Describe the bug**
First for all, I want to thank you for the initiative. In the second, i open the bot and, i open the game on stean or kongregate, i click in find start, and this working normally, but when i click in auto mode, the bot stop to working, i have a question, the bot doesnt work more or  I'm going wrong

**Version(please complete the following information):**
 - Steam or Kongregate
Both

**Comment by tiemonl** [comment]
Can you give me more information please?

What OS are you using? What version of the program are you using? What kind of error are you getting?

**Comment by refoz** [comment]
I have Windows 10 x64, looking this video, I recorded now... https://www.youtube.com/watch?v=w97lYCm77eI&feature=youtu.be

**Comment by tiemonl** [comment]
Look at the [README](https://github.com/tiemonl/Bit-Heroes-Fishing-Bot#setting-up-the-program). You need to press find start location on the fishing start screen where you can pick your rod and bait.

**Comment by refoz** [comment]
Yeah, i try but nothing :/ https://youtu.be/USWtCmB4-68 <-- Look

**Comment by tiemonl** [comment]
Press find start location when you are on that screen. The program needs the coordinate of that screen.

**Comment by refoz** [comment]
Sorry, doesnt work yet :/  https://www.youtube.com/watch?v=LGXT1DC6fEQ&feature=youtu.be <---

**Comment by tiemonl** [comment]
Can you send me a picture of your display settings in windows 10?

**Comment by refoz** [comment]
![screenshot_3](https://user-images.githubusercontent.com/33155161/44680631-b656a680-aa14-11e8-9561-eea4754a572b.png)

**Comment by tiemonl** [comment]
Sorry. The display settings for your monitor resolution and such, not the system settings.

**Comment by refoz** [comment]
what the resolution to work?

**Comment by tiemonl** [comment]
This screen: ![](https://cnet2.cbsistatic.com/img/NGEFtOhroxN3g5MtkQGE-6NQ2qI=/620x0/2018/05/16/a945b0cf-df92-47b1-8fc2-66a4be89b8e0/windows-10-display-settings.jpg)

**Comment by tiemonl** [comment]
You need to use your default resolution and 100% scaling

**Comment by refoz** [comment]
Now working, tnx brother!!

**Comment by tiemonl** [comment]
No problem, glad I got it working for you!
